"""Scheduled reports — weekly email summary of device health."""
import uuid
from datetime import datetime, timedelta
from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, func
from models import Device, MetricHistory, TaskResult, LogEntry
from database import get_db

router = APIRouter()

async def build_report_html(db: AsyncSession) -> str:
    # Devices
    dev_result = await db.execute(select(Device))
    devices = dev_result.scalars().all()
    online  = [d for d in devices if d.status == "online"]
    offline = [d for d in devices if d.status == "offline"]

    # Task results last 7 days
    since = datetime.utcnow() - timedelta(days=7)
    tr_result = await db.execute(
        select(TaskResult).where(TaskResult.started_at >= since)
    )
    task_results = tr_result.scalars().all()
    t_success = sum(1 for r in task_results if r.exit_code == 0)
    t_failed  = sum(1 for r in task_results if r.exit_code not in (None,0))

    rows = ""
    for d in sorted(devices, key=lambda x: x.hostname):
        status_color = "#00e5ff" if d.status=="online" else "#666"
        rows += f"""<tr>
            <td>{d.label or d.hostname}</td>
            <td style="color:{status_color}">{d.status}</td>
            <td>{d.platform}</td>
            <td>{f"{d.cpu_percent:.0f}%" if d.cpu_percent else "—"}</td>
            <td>{f"{d.ram_percent:.0f}%" if d.ram_percent else "—"}</td>
            <td>{f"{d.disk_percent:.0f}%" if d.disk_percent else "—"}</td>
            <td>{d.last_seen.strftime("%Y-%m-%d %H:%M") if d.last_seen else "—"}</td>
        </tr>"""

    return f"""<html><body style="font-family:monospace;background:#0a0a0a;color:#e0e0e0;padding:24px">
<h1 style="color:#00e5ff;border-bottom:1px solid #222;padding-bottom:12px">
  📊 Sovereign RMM — Weekly Report<br>
  <small style="font-size:14px;color:#666">{datetime.utcnow().strftime("%B %d, %Y")}</small>
</h1>
<div style="display:flex;gap:24px;margin:20px 0">
  <div style="background:#111;padding:16px;border-radius:6px;flex:1;border:1px solid #222">
    <div style="font-size:28px;font-weight:700;color:#00e5ff">{len(online)}</div>
    <div style="color:#888;font-size:12px">DEVICES ONLINE</div>
  </div>
  <div style="background:#111;padding:16px;border-radius:6px;flex:1;border:1px solid #222">
    <div style="font-size:28px;font-weight:700;color:#666">{len(offline)}</div>
    <div style="color:#888;font-size:12px">DEVICES OFFLINE</div>
  </div>
  <div style="background:#111;padding:16px;border-radius:6px;flex:1;border:1px solid #222">
    <div style="font-size:28px;font-weight:700;color:#69ff47">{t_success}</div>
    <div style="color:#888;font-size:12px">TASKS SUCCEEDED (7d)</div>
  </div>
  <div style="background:#111;padding:16px;border-radius:6px;flex:1;border:1px solid #222">
    <div style="font-size:28px;font-weight:700;color:#ff5252">{t_failed}</div>
    <div style="color:#888;font-size:12px">TASKS FAILED (7d)</div>
  </div>
</div>
<h2 style="color:#00e5ff;font-size:14px;margin-top:24px">ALL DEVICES</h2>
<table style="width:100%;border-collapse:collapse;font-size:12px">
  <thead><tr style="background:#111;color:#888">
    <th style="padding:8px;text-align:left">Device</th><th>Status</th>
    <th>Platform</th><th>CPU</th><th>RAM</th><th>Disk</th><th>Last Seen</th>
  </tr></thead>
  <tbody>{rows}</tbody>
</table>
<p style="color:#444;font-size:11px;margin-top:24px">Generated by Sovereign RMM</p>
</body></html>"""


@router.get("/preview")
async def preview_report(db: AsyncSession = Depends(get_db)):
    """Returns report HTML for preview."""
    html = await build_report_html(db)
    from fastapi.responses import HTMLResponse
    return HTMLResponse(html)


@router.post("/send")
async def send_report(db: AsyncSession = Depends(get_db)):
    """Send the weekly report email now."""
    from routes.email_svc import get_smtp_settings, send_email_raw
    smtp = await get_smtp_settings(db)
    to   = smtp.get("alert_email","")
    if not to:
        from fastapi import HTTPException
        raise HTTPException(400, "No alert email set in Settings → Email Alerts")
    html = await build_report_html(db)
    await send_email_raw(smtp, to, f"[Sovereign RMM] Weekly Report — {datetime.utcnow().strftime('%B %d, %Y')}", html)
    return {"status": "sent", "to": to}
